# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - uses: subosito/flutter-action@v1
      with:
        channel: "beta"
    # - name: Generate coverage report
    #   run: |
    #     pip install pytest
    #     pip install pytest-cov
    #     pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token:  ed46e133-6cdc-4067-9379-0bc765984489
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage1.xml,./coverage2.xml
        flags: unittests
        name: codecov-umbrella
        # path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
    - run: flutter pub get
    - run: flutter analyze
    - run: flutter test
    - name: Codebase testing
      run: flutter test --coverage
    - name: Present current coverage in PR
      uses: codecov/codecov-action@v2.1.0      
      with:
        verbose: true
    - name: Test acceptable level of code coverage
      uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
      with:
          path: './coverage/lcov.info'
          min_coverage: 10

# jobs:
#   Flutter-Codebase-Check: 
#     name: Run flutter test and analyze
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-java@v1
#         with:
#           java-version: "12.x"
#       - uses: subosito/flutter-action@v1
#         with:
#           channel: "beta"
#       - run: flutter pub get
#       - run: flutter analyze
#       # - run: flutter test

#   Flutter-Testing:
#     name: Testing codebase
#     runs-on: ubuntu-latest
#     needs: Flutter-Codebase-Check
#     steps:
#       - uses: actions/checkout@v2
#       - uses: codecov/codecov-action@v2
#         with:
#           token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
#           files: ./coverage1.xml,./coverage2.xml # optional
#           flags: unittests # optional
#           name: codecov-umbrella # optional
#           fail_ci_if_error: true # optional (default = false)
#           verbose: true # optional (default = false)
#       - uses: actions/setup-java@v1
#         with:
#           java-version: "12.x"
#       - uses: subosito/flutter-action@v1
#         with:
#           channel: "beta"
#       - run: flutter pub get
#       - run: flutter analyze
#       - run: flutter test
#       - name: Codebase testing
#         run: flutter test --coverage
#       - name: Present current coverage in PR
#         uses: codecov/codecov-action@v2.1.0      
#         with:
#           verbose: true
#       - name: Test acceptable level of code coverage
#         uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
#         with:
#             path: './coverage/lcov.info'
#             min_coverage: 10
#       - run: genhtml coverage/lcov.info -o coverage/html
            
#   Android-Build:
#     name: Testing build for android
#     runs-on: ubuntu-latest
#     needs: Flutter-Codebase-Check
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-java@v1
#         with:
#           java-version: "12.x"
#       - uses: subosito/flutter-action@v1
#         with:
#           channel: "beta"
#       - run: flutter pub get
#       - run: flutter analyze
#       - run: flutter test
#       - name: Building for android
#         run: flutter build apk

#   iOS-Build:
#     name: Testing build for iOS
#     runs-on: macos-latest
#     needs: Flutter-Codebase-Check
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-java@v1
#         with:
#           java-version: "12.x"
#       - uses: subosito/flutter-action@v1
#         with:
#           channel: "beta"
#       - run: flutter pub get
#       - run: flutter analyze
#       - run: flutter test
#       - name: Building for ios
#         run: flutter build ios --release --no-codesign